### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mastertinner** [techniq/mui-virtualized-table#10]
It would be great to have native TypeScript support and typings for this project.

**Comment by MarkLeMerise** [comment]
Hi @techniq, thanks for an awesome little library! I am currently integrating this into a TypeScript project and have written a fair amount of the `.d.ts` typings file already. Would you be open to PR to this project? Or would you rather it be contributed to the DefinitelyTyped collection?

Ideally, the typings would live next to the module they describe, but I don't want to put the burden of future type maintenance onto the library maintainer if they don't want it.

**Comment by techniq** [comment]
@MarkLeMerise I would greatly appreciate a PR and maintain the types in the project.  I wouldn't oppose even having the library written in Typescript.  All my new projects are written in Typescript now, but I haven't had time to go back and update some of my other projects.

I currently maintain types for [mui-table](https://github.com/techniq/mui-table/blob/master/index.d.ts) and [react-fetch-component](https://github.com/techniq/react-fetch-component) (and a few others).  mui-table's types are similar to mui-virtualized-table so there might be some reuse there (generic TData would with a default would be nice to replicate here).

**Comment by MarkLeMerise** [comment]
Sounds good! I'll take a look at the `mui-table` typings and try to use them as a reference. Not sure when I'll get around to opening a PR, but I'm happy to hear you're open to it!

**Comment by mastertinner** [comment]
Thanks for the great PR, @MarkLeMerise! However, I think there's a bug in it. For me, it doesn't work yet because TypeScript still complains about `error TS7016: Could not find a declaration file for module 'mui-virtualized-table'.`.

I think it's because in `package.json`, you wrote the following:

```json
"types": "index.d.ts",
```

it should, however, say the following:

```json
"typings": "index.d.ts",
```

**Comment by MarkLeMerise** [comment]
@mastertinner You're right, I just experienced the same issue after upgrading to 2.2.0. I think it's because the `index.d.ts` file is not being included in the `npm install`, so maybe it's not being published with the package? I'm not sure what your publication process entails so I defer to you guys on the best way to handle this.

**Comment by techniq** [comment]
@MarkLeMerise @mastertinner should be fixed in 2.2.1.  Needed to include the `index.d.ts` in [files](https://github.com/techniq/mui-virtualized-table/blob/master/package.json#L9) to be published to npm (this has bit me before)

**Comment by MarkLeMerise** [comment]
@techniq mybad, totally missed that. Thanks for resolving so quickly!

**Comment by techniq** [comment]
@MarkLeMerise Thanks for the typings!
